[project]
name = "amarillo-metrics"
version = "0.0.2"
description = "Prometheus metrics for Amarillo"
readme = "README.md"

dependencies = [
    "fastapi",
    "amarillo",
    "prometheus-fastapi-instrumentator",
    "prometheus-client"
]